[package]
name = "scripting"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.18"
engine = {path = "../../crates/engine"}
danmaku = {path = "../../crates/danmaku"}
content = {path = "../../crates/content"}
slotmap = "1.1.1"
glam = "0.33.2"
mlua = {version = "0.12.0", features = ["lua54", "vendored"] }
